# Site settings
title: aiops.ru на русском языке

description: Собираем материалы связанные с разработкой и развертыванием приложений вокруг экосистемы AI

keywords: AIOPS, MLOPS, Clouds, Linux, Docker, Kubernetes

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://aiops.ru' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
