# Site settings
title: dlops.ru на русском языке

description: Собираем материалы связанные с разработкой и развертыванием приложений вокруг экосистемы Git

keywords: DLOPS, Clouds, Linux, Docker, Kubernetes, GitHub Actions, FluxCD

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://dlops.ru' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
    - jekyll-sitemap
